package com.example.elden_ring_build;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.example.elden_ring_build.Model.PlayerCharacter;

public class PlayerCharacterTest {

    private PlayerCharacter playerCharacter;

    @BeforeEach
    public void setUp() {
        // Creating a PlayerCharacter object before each test
        playerCharacter = new PlayerCharacter(
                "EldenLord", "Strength", 100, 40, 20, 10, 30, 15, 50, 40, 30,
                "Greatsword", "Havel's Armor", "Tower Shield", "Radagon's Scarseal");
    }

    @Test
    public void testPlayerCharacterConstructor() {
        // Verify that the constructor correctly initializes fields
        assertNotNull(playerCharacter);
        assertEquals("EldenLord", playerCharacter.getName());
        assertEquals("Strength", playerCharacter.getBuildType());
        assertEquals(100, playerCharacter.getLevel());
        assertEquals(40, playerCharacter.getStrength());
        assertEquals(20, playerCharacter.getDexterity());
        assertEquals(10, playerCharacter.getIntelligence());
        assertEquals(30, playerCharacter.getFaith());
        assertEquals(15, playerCharacter.getArcane());
        assertEquals(50, playerCharacter.getVigor());
        assertEquals(40, playerCharacter.getEndurance());
        assertEquals(30, playerCharacter.getMind());
        assertEquals("Greatsword", playerCharacter.getWeapon());
        assertEquals("Havel's Armor", playerCharacter.getArmor());
        assertEquals("Tower Shield", playerCharacter.getShield());
        assertEquals("Radagon's Scarseal", playerCharacter.getTalisman());
    }

    @Test
    public void testSettersAndGetters() {
        // Test the setters and getters generated by Lombok
        playerCharacter.setName("NewName");
        playerCharacter.setBuildType("Dexterity");
        playerCharacter.setLevel(120);
        playerCharacter.setStrength(50);

        // Verify the values were updated
        assertEquals("NewName", playerCharacter.getName());
        assertEquals("Dexterity", playerCharacter.getBuildType());
        assertEquals(120, playerCharacter.getLevel());
        assertEquals(50, playerCharacter.getStrength());
    }

    @Test
    public void testDefaultConstructor() {
        // Test default constructor behavior (without parameters)
        PlayerCharacter defaultPlayer = new PlayerCharacter();
        assertNotNull(defaultPlayer);
        // Optionally, check if fields are null or set to default values
        assertEquals(0, defaultPlayer.getLevel()); // As 'level' is an int (primitive), it defaults to 0
        assertNull(defaultPlayer.getName()); // 'name' is a String, so defaults to null
        assertNull(defaultPlayer.getWeapon()); // 'weapon' is a String, so defaults to null
    }
}
